version: '3.7'
services:
  bgpspeaker:
    image: rust:1.69.0
    hostname: bgpspeaker
    container_name: bgpspeaker
    working_dir: "/home/bgpspeaker"
    volumes:
      - ../component/bgpspeaker/:/workspace:cached
    command: /bin/sh -c "while :; do sleep 10; done"

  keepalived:

  loadbalancer:

  dbmgr:

  db:
    image: redis:7.2-rc1
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
